
import React from 'react';

const CopyRight  = () => {
  const styles = {
    display: 'block',        
    fontWeight: 'bold',
    height: '57vh',
    margin: '200px 200px 200px 200px'
  };

  const heading = {
    display: 'inline-block',
    
    
  };
  
  const mainPart = {
    display: 'inline-block',
    
  };

  return (
    <div style={styles}>
      <div style={heading}> 
        Copyright
      </div>
      <body style={mainPart}>
        TERMS AND CONDITIONS OF USE AND SALE THE WEBSITE (THE “SITE”) IS OPERATED BY HARMAN INTERNATIONAL INDUSTRIES (“HARMAN”) FOR YOUR USE AND INFORMATION. PRODUCTS PURCHASED THROUGH THIS SITE ARE SOLD AND SHIPPED BY JAM INDUSTRIES LIMITED (THE “COMPANY”). YOUR USE OF THE SITE IS SUBJECT TO THE FOLLOWING TERMS AND CONDITIONS OF USE AND SALE (THE “TERMS AND CONDITIONS”) AND ALL APPLICABLE LAWS. BY ACCESSING AND BROWSING THE SITE, YOU ACCEPT, WITHOUT LIMITATION OR QUALIFICATION, THE TERMS AND CONDITIONS. IF YOU DO NOT AGREE WITH ANY OF THE TERMS AND CONDITIONS, PLEASE DO NOT USE THE SITE. THESE TERMS AND CONDITIONS ARE A LEGAL AGREEMENT AMONG YOU, HARMAN AND THE COMPANY CONCERNING EACH PURCHASE OF PRODUCTS OFFERED ON THE SITE. IF YOU DO NOT ACCEPT THESE TERMS AND CONDITIONS, OR ANY PART OF THEM, YOU MAY NOT USE THE SITE TO PURCHASE ANY OF THE PRODUCTS AVAILABLE ON THE SITE. HARMAN AND THE COMPANY RESERVE THE RIGHT TO CHANGE, MODIFY, ALTER, ADD, REMOVE OR OTHERWISE UPDATE THE TERMS AND CONDITIONS (OR ANY PORTION THEREOF) APPLICABLE TO THE SITE WITHOUT PRIOR WRITTEN NOTICE AT ANY TIME, AND FROM TIME TO TIME, AT THEIR SOLE DISCRETION. WE WILL NOTIFY YOU OF ANY SUCH CHANGES, MODIFICATIONS, ALTERATIONS OR UPDATES TO THE SITE BY POSTING NOTICE OF SAME ON THE SITE. FOLLOWING THE POSTING OF ANY SUCH NOTICE, YOUR CONTINUED USE OF THE SITE WILL CONSTITUTE YOUR ACCEPTANCE OF THE NEW TERMS AND CONDITIONS AND OTHER POLICIES, AS MODIFIED, AND YOU WILL BE BOUND BY SAID NEW TERMS AND CONDITIONS AND POLICIES. THE SITE IS NOT INTENDED FOR ACCESS OR USE OUTSIDE OF CANADA. YOU ARE RESPONSIBLE FOR ENSURING THAT YOUR ACCESS TO THE SITE AND THE INFORMATION AND MATERIAL AVAILABLE ON OR THROUGH IT ARE LEGAL IN EACH JURISDICTION IN OR THROUGH WHICH YOU ACCESS OR VIEW THE SITE AND SUCH INFORMATION AND MATERIAL. THE TERMS “WE”, “US”, AND “OUR” USED IN THE TERMS AND CONDITIONS REFER TO HARMAN AND THE COMPANY. WE URGE YOU TO READ THE TERMS AND CONDITIONS CAREFULLY, AS THEY INCLUDE PROVISIONS SUCH AS LIMITATION OF LIABILITY, DISPUTE RESOLUTION AND OTHER PROVISIONS THAT MAY LIMIT YOUR RIGHTS.
      </body>
  </div>
  );
};

export default CopyRight;


